---
language: python
services: docker

matrix:
  include:
    - os: linux
      dist: xenial

before_script:
  - cd ../
  - mv ansible-role-common common
  - cd common

install:
  - pip install molecule docker

script:
  - molecule test
